### ISSUE TITLE
Btsnoop capture of the BLE traffic

### ISSUE THREAD

**Issue by syssi** [RoboDurden/AntBms-Arduino#1]
Hi,

I've seen your [attempts talking to your 16ZMUB using bluetooth](https://www.photovoltaikforum.com/thread/183467-wo-neuste-ant-bms-android-app-oder-alternativen-oder-uart-protokoll/). I assume RFComm / a serial connection via bluetooth isn't used anymore. Instead some BLE services are used to send commands and subscribe to notifications. I would like to implement the BLE communication [here](https://github.com/syssi/esphome-ant-bms/issues/48) but I need a btsnoop capture. Could you provide such a capture?

Kind regards,

Sebastian

**Comment by RoboDurden** [comment]
Well, my attempts failed and as I have also a hybrid inverter with rs232 in my little solar truck i go for a esp32 with serial wires and a combined Bluetooth connection to my smartphone.
Sorry, but I can not help you with sniffing the antBms Bluetooth data.

**Comment by syssi** [comment]
It's a task of round about 30 minutes if you follow this guide: https://medium.com/@charlie.d.anderson/how-to-get-the-bluetooth-host-controller-interface-logs-from-a-modern-android-phone-d23bde00b9fa

Could you do me the favor? :-)

**Comment by RoboDurden** [comment]
For sure i would do you a 2 hours favor, i would like to hack many commercial Bluetooth devices. So of course I have already followed your links this morning and took a glimpse at that tutorial.
I have a pixel 1 with Android 10 and a pixel 2 with Android 11 both not rooted.
As I am on the road with my little solar camper it takes two weeks to be back where my solar truck with the antBms is located.

Here I have Bluetooth earbuds and a Bluetooth anti snoring mask.

Tell me if proceeding with these would also help you.

And yes i would like to learn how to hack ble protocols.

**Comment by RoboDurden** [comment]
And I have Android studio setup so adb should be no problem.
Yes sure i will be happy to assist you writing a ble connection.

**Comment by syssi** [comment]
Rooting isn't important because the btsnoop capture is part of the bug report (zip bundle) if enabled at the settings beforehand. I will write down some instructions this evening. Thanks for your support in advance!

**Comment by RoboDurden** [comment]
As far as I understand you don't have a compatible Android phone and you only want the antBms logs. That will have to wait until I am back at my train station.

**Comment by syssi** [comment]
That's correct. My goal is a btsnoop capture of the ANT BMS traffic. Have nice trip! I will ping you in a few weeks. I hope we can convince one of your android devices to spit out the capture. :-)

**Comment by syssi** [comment]
Thanks for your support!
